# Generated by Django 5.2.4 on 2025-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stok takip kodu - Otomatik oluşturulur', max_length=50, null=True, unique=True, verbose_name='Ürün Kodu'),
        ),
    ]
