# Generated by Django 5.2.4 on 2025-09-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_add_focal_points'),
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
    ]
