# Generated by Django 5.2.4 on 2025-09-25 18:34

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_0001_add_focal_points_0002_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='focal_point_x',
        ),
        migrations.RemoveField(
            model_name='product',
            name='focal_point_y',
        ),
        migrations.AddField(
            model_name='product',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Ürün kartlarında gösterilecek kırpılmış resim' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Resim' %}"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Ürün için tam boyut orijinal resim (modal/detay için)' %}", max_length=255, verbose_name="{% trans 'Orijinal Resim' %}"),
        ),
    ]
