# Generated by Django 5.2.4 on 2025-12-18 12:04

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_focal_point_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Ürün kartlarında gösterilecek kırpılmış resim', max_length=255, verbose_name='Kırpılmış Resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.cloudinary_fields.RawImageField(blank=True, help_text='Ürün için tam boyut orijinal resim (modal/detay için)', max_length=255, verbose_name='Orijinal Resim'),
        ),
    ]
