# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_cropped_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_es',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_es',
        ),
    ]
