# Generated by Django 5.2.4 on 2025-09-08 09:05

import core.cloudinary_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_de', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, help_text='Otomatik oluşturulur. SEO dostu URL için kullanılır.', max_length=250, unique=True, verbose_name='SEO URL')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('alt_text', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, verbose_name='Alt Metin (SEO)')),
                ('alt_text_tr', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_en', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_de', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_fr', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_es', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_ru', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_ar', models.CharField(blank=True, help_text='Görsel için SEO alt metni (max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('media_type', models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], max_length=5, verbose_name='Medya Tipi')),
                ('image', core.cloudinary_fields.OptimizedImageField(blank=True, max_length=255, verbose_name='Resim')),
                ('video', core.cloudinary_fields.OptimizedVideoField(blank=True, help_text='MP4, WebM formatlarını destekler', max_length=255, verbose_name='Video Dosyası')),
                ('video_url', models.URLField(blank=True, help_text="YouTube veya Vimeo URL'si", verbose_name='Video URL')),
                ('meta_title', models.CharField(blank=True, help_text='Arama motorları için başlık (max 60 karakter)', max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, help_text='Arama motorları için açıklama (max 160 karakter)', max_length=160, verbose_name='Meta Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['order', '-created_at'],
            },
            bases=(core.cloudinary_fields.SEOImageMixin, models.Model),
        ),
    ]
