# Generated by Django 5.2.4 on 2025-09-23 19:25

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_add_focal_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=core.cloudinary_fields.RawImageField(blank=True, max_length=255, verbose_name='Resim'),
        ),
    ]
