# Generated by Django 5.2.4 on 2025-09-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cropped_image_url',
            field=models.URLField(blank=True, help_text="Otomatik oluşturulan kırpılmış resim URL'si", verbose_name='Kırpılmış Resim URL'),
        ),
    ]
