# Generated by Django 5.2.4 on 2025-09-25 18:34

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_cropped_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='cropped_image_url',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='focal_point_x',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='focal_point_y',
        ),
        migrations.AddField(
            model_name='gallery',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Kartlarda gösterilecek kırpılmış resim' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Resim' %}"),
        ),
    ]
