# Generated by Django 5.2.4 on 2025-12-18 12:04

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_gallery_cropped_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Kartlarda gösterilecek kırpılmış resim', max_length=255, verbose_name='Kırpılmış Resim'),
        ),
    ]
