# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_cropped_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='alt_text_es',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_es',
        ),
    ]
