# Generated by Django 5.2.4 on 2025-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_footer',
            field=models.BooleanField(default=False, help_text="Footer'da gösterilmesini istediğiniz hizmetleri işaretleyin (max 6 adet)", verbose_name="Footer'da Göster"),
        ),
    ]
