# Generated by Django 5.2.4 on 2025-09-25 18:34

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_service_is_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Kartlarda gösterilecek kırpılmış resim' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Resim' %}"),
        ),
        migrations.AddField(
            model_name='service',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Hizmet kartlarında gösterilecek kırpılmış resim' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Resim' %}"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Ekip kartlarında gösterilecek kırpılmış fotoğraf' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Fotoğraf' %}"),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Tam boyut orijinal resim (modal/detay için)' %}", max_length=255, null=True, verbose_name="{% trans 'Orijinal Resim' %}"),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text="{% trans 'Hizmet için tam boyut orijinal resim' %}", max_length=255, verbose_name="{% trans 'Orijinal Resim' %}"),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text="{% trans 'Tam boyut orijinal fotoğraf (modal/detay için)' %}", max_length=255, verbose_name="{% trans 'Orijinal Fotoğraf' %}"),
        ),
    ]
