# Generated by Django 5.2.4 on 2025-12-18 12:04

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_cropped_image_service_cropped_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Kartlarda gösterilecek kırpılmış resim', max_length=255, verbose_name='Kırpılmış Resim'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Tam boyut orijinal resim (modal/detay için)', max_length=255, null=True, verbose_name='Orijinal Resim'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Hizmet kartlarında gösterilecek kırpılmış resim', max_length=255, verbose_name='Kırpılmış Resim'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text='Hizmet için tam boyut orijinal resim', max_length=255, verbose_name='Orijinal Resim'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text='Ekip kartlarında gösterilecek kırpılmış fotoğraf', max_length=255, verbose_name='Kırpılmış Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text='Tam boyut orijinal fotoğraf (modal/detay için)', max_length=255, verbose_name='Orijinal Fotoğraf'),
        ),
    ]
