# Generated by Django 5.2.4 on 2025-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_cropped_image_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış uzmanlık alanları (ör: Python, Django, React)', max_length=500, verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
