# Generated by Django 5.2.4 on 2025-12-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_teammember_email_teammember_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
    ]
