# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_teammember_email_remove_teammember_expertise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='meta_description_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_title_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='mission_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='short_description_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='story_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='about',
            name='vision_es',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio_es',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position_es',
        ),
    ]
