# Generated by Django 5.2.4 on 2025-09-08 09:05

import core.cloudinary_fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', core.cloudinary_fields.OptimizedImageField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(default='Şirket Adı', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_link', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('site_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İşletme Ayarları',
                'verbose_name_plural': 'İşletme Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('review', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylı')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Site Başlığı')),
                ('favicon', core.cloudinary_fields.OptimizedImageField(blank=True, max_length=255, verbose_name='Favicon')),
                ('logo', core.cloudinary_fields.OptimizedImageField(blank=True, max_length=255, verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('analytics_code', models.TextField(blank=True, verbose_name='Analytics Kodu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='MediaMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', core.cloudinary_fields.OptimizedImageField(blank=True, max_length=255, verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, help_text='Görsel için SEO alt metni', max_length=125, verbose_name='Alt Metin (SEO)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (İngilizce)')),
                ('source_en', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (İngilizce)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (İngilizce)')),
                ('title_de', models.CharField(blank=True, max_length=200, verbose_name='Başlık (Almanca)')),
                ('source_de', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (Almanca)')),
                ('description_de', models.TextField(blank=True, verbose_name='Açıklama (Almanca)')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='Başlık (Fransızca)')),
                ('source_fr', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (Fransızca)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Açıklama (Fransızca)')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='Başlık (İspanyolca)')),
                ('source_es', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (İspanyolca)')),
                ('description_es', models.TextField(blank=True, verbose_name='Açıklama (İspanyolca)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Başlık (Rusça)')),
                ('source_ru', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (Rusça)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Açıklama (Rusça)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Başlık (Arapça)')),
                ('source_ar', models.CharField(blank=True, max_length=100, verbose_name='Kaynak (Arapça)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Açıklama (Arapça)')),
            ],
            options={
                'verbose_name': 'Basın Haberi',
                'verbose_name_plural': 'Basın Haberleri',
                'ordering': ['order', '-publish_date'],
            },
            bases=(core.cloudinary_fields.SEOImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Okundu'), ('replied', 'Yanıtlandı'), ('spam', 'Spam')], default='new', max_length=10, verbose_name='Durum')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTranslationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('ru', 'Русский'), ('ar', 'العربية')], default='tr', help_text='Dashboard arayüzünün görüntüleneceği dil', max_length=7, verbose_name='Dashboard Dili')),
                ('primary_language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('ru', 'Русский'), ('ar', 'العربية')], default='tr', help_text='Site içeriği için ana dil (her zaman dahil olur)', max_length=7, verbose_name='Ana Dil')),
                ('enabled_languages', models.JSONField(default=list, help_text='Bu kullanıcının site içeriği için çeviri yapacağı diller', verbose_name='Site İçin Aktif Diller')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation_settings', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Dashboard Çeviri Ayarları',
                'verbose_name_plural': 'Dashboard Çeviri Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('message', 'Mesaj'), ('review', 'Yorum'), ('product', 'Ürün'), ('system', 'Sistem'), ('user', 'Kullanıcı')], default='system', max_length=20, verbose_name='Tip')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Yönlendirme URL')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Açıklama')),
                ('image', core.cloudinary_fields.OptimizedImageField(max_length=255, verbose_name='Ürün Görseli')),
                ('alt_text', models.CharField(blank=True, help_text='Ürün görseli için SEO alt metni', max_length=125, verbose_name='Alt Metin (SEO)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Fiyat')),
                ('stock', models.IntegerField(blank=True, default=None, null=True, verbose_name='Stok Durumu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
            bases=(core.cloudinary_fields.SEOImageMixin, models.Model),
        ),
    ]
