# Generated by Django 5.2.4 on 2025-12-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessSettings',
        ),
    ]
