# Generated by Django 5.2.4 on 2025-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('subject_tr', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_en', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_de', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_fr', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_es', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_ru', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('subject_ar', models.CharField(max_length=200, null=True, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('message_tr', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_en', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_de', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_fr', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_es', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_ru', models.TextField(null=True, verbose_name='Mesaj')),
                ('message_ar', models.TextField(null=True, verbose_name='Mesaj')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
