# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_es',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject_es',
        ),
    ]
