# Generated by Django 5.2.4 on 2025-09-08 09:05

import core.cloudinary_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_de', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('description_tr', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_de', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_fr', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_es', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_ru', models.TextField(null=True, verbose_name='Açıklama')),
                ('description_ar', models.TextField(null=True, verbose_name='Açıklama')),
                ('image', core.cloudinary_fields.OptimizedImageField(max_length=255, verbose_name='Görsel')),
                ('alt_text', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, verbose_name='Alt Metin (SEO)')),
                ('alt_text_tr', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_en', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_de', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_fr', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_es', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_ru', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('alt_text_ar', models.CharField(blank=True, help_text='Görsel için alternatif metin. SEO için önemli! (Max 125 karakter)', max_length=125, null=True, verbose_name='Alt Metin (SEO)')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Buton Metni')),
                ('button_text_tr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_de', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_es', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_text_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Metni')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Buton URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Carousel Slayt',
                'verbose_name_plural': 'Carousel Slaytlar',
                'ordering': ['order'],
            },
            bases=(core.cloudinary_fields.SEOImageMixin, models.Model),
        ),
    ]
