# Generated by Django 5.2.4 on 2025-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Arama motorları için açıklama (max 160 karakter)', max_length=160, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Arama motorları için başlık (max 60 karakter)', max_length=60, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur. Slide detay sayfası için kullanılır.', max_length=250, unique=True, verbose_name='SEO URL'),
        ),
    ]
