# Generated by Django 5.2.4 on 2025-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carouselslide_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Hakkımızda', help_text='Ana butonun yanındaki ikinci buton metni', max_length=50, verbose_name='İkinci Buton Metni'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='secondary_button_url',
            field=models.CharField(blank=True, help_text='İkinci buton linki. Boş bırakılırsa hakkımızda sayfasına yönlendirir', max_length=200, verbose_name='İkinci Buton URL'),
        ),
    ]
