# Generated by Django 5.2.4 on 2025-09-25 18:34

import core.cloudinary_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carouselslide_secondary_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='cropped_image',
            field=core.cloudinary_fields.OptimizedImageField(blank=True, help_text="{% trans 'Carousel'da gösterilecek kırpılmış görsel' %}", max_length=255, verbose_name="{% trans 'Kırpılmış Görsel' %}"),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text="{% trans 'Tam boyut orijinal görsel (modal/detay için)' %}", max_length=255, verbose_name="{% trans 'Orijinal Görsel' %}"),
        ),
    ]
