# Generated by Django 5.2.4 on 2025-12-18 12:04

import core.cloudinary_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_carouselslide_cropped_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='cropped_image',
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='image',
            field=core.cloudinary_fields.OptimizedImageField(help_text='Carousel görseli (Önerilen: 1920x1080)', max_length=255, verbose_name='Slayt Görseli'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='SEO URL'),
        ),
    ]
