# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_carouselslide_cropped_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='alt_text_es',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='button_text_es',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='title_es',
        ),
    ]
