# Generated by Django 5.2.4 on 2025-09-08 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, verbose_name='Ad Soyad')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, "Değerlendirme 1'den küçük olamaz"), django.core.validators.MaxValueValidator(5, "Değerlendirme 5'ten büyük olamaz")], verbose_name='Değerlendirme')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('comment_tr', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_en', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_de', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_fr', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_es', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_ru', models.TextField(null=True, verbose_name='Yorum')),
                ('comment_ar', models.TextField(null=True, verbose_name='Yorum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='Resim')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylı')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
