# Generated by Django 5.2.4 on 2025-09-16 20:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Oturum Anahtarı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('necessary_cookies', models.BooleanField(default=True, verbose_name='Zorunlu Çerezler')),
                ('functional_cookies', models.BooleanField(default=False, verbose_name='Fonksiyonel Çerezler')),
                ('analytics_cookies', models.BooleanField(default=False, verbose_name='Analitik Çerezler')),
                ('marketing_cookies', models.BooleanField(default=False, verbose_name='Pazarlama Çerezleri')),
                ('consent_date', models.DateTimeField(auto_now_add=True, verbose_name='Onay Tarihi')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Çerez Onayı',
                'verbose_name_plural': 'Çerez Onayları',
                'ordering': ['-consent_date'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Gizlilik Politikası'), ('terms', 'Kullanım Şartları'), ('cookies', 'Çerez Politikası')], help_text='Yasal sayfa türünü seçin', max_length=20, unique=True, verbose_name='Sayfa Türü')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='SEO URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Yasal sayfa içeriğini buraya girin', verbose_name='İçerik')),
                ('meta_title', models.CharField(blank=True, help_text='Arama motorları için başlık (max 60 karakter)', max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, help_text='Arama motorları için açıklama (max 160 karakter)', max_length=160, verbose_name='Meta Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Yasal Sayfa',
                'verbose_name_plural': 'Yasal Sayfalar',
                'ordering': ['page_type'],
            },
        ),
    ]
