# Generated by Django 5.2.4 on 2025-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cookieconsent_legalpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pdf_catalog_title_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_description_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_keywords_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_title_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name_es',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_tagline_es',
        ),
    ]
